apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: backend
spec:
  destination:
    namespace: prod
  precedence: 1
  route:
  - labels:
      app: backend
      version: v1
      weight: 100
