apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    openshift.io/image.dockerRepositoryCheck: 2018-03-31T16:56:41Z
  creationTimestamp: null
  generation: 2
  labels:
    app: backend
  name: fedora
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: fedora:27
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/staging/fedora:27
    generation: 2
    importPolicy: {}
    name: "27"
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
