apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: frontend:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: frontend
    git:
      uri: https://github.com/vrutkovs/istio-sample.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: fedora:27
        namespace: staging
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: kBCZvqEm0AT6mwiUXS0N
    type: GitHub
  - generic:
      secret: 0HMfKDNchD32CqOApTge
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
