apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: backend
  name: backend
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: backend:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: backend
    git:
      uri: https://github.com/vrutkovs/istio-sample.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: fedora:27
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: ezDfStY_USVyxZylUNyD
    type: GitHub
  - generic:
      secret: QjpvSDynrFoi1BbnPmkc
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
